CREATE TABLE events
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE orders
(
  guest_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL
);

CREATE TABLE guests
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

